### ISSUE TITLE
Request for explanation 

### ISSUE THREAD

**Issue by thericeking** [StochasticTinkr/PerformanceTuner#2]
Hello and thank you for this awesome mod.

Can you please better explain what each parameter does?

[Simple]
; Set this to your desired framerate, or your monitor refresh rate if using v-sync
fTargetFPS=60.0
fTargetLoad=100.0 <-- What does this do?
; The default settings give you slightly worse than medium -> slightly better than high
fShadowDirDistanceMin=3000.0 
fShadowDirDistanceMax=20000.0 <-- Is this the highest the game can go?
; In simple mode there is no framerate cap, use this if you use vsync or you're unsure
bSimpleMode=0 <-- Can I get a better explanation? 
; By default adjust the godrays
bAdjustGRQuality=1 <-- No way to control a GR quality range?
; These control at what shadow dist the godray settings should be changed
fGRQualityShadowDist1=8000.0 <--Low?
fGRQualityShadowDist2=12000.0 <-- Medium 
fGRQualityShadowDist3=16000.0 <-- High
[Advanced]
; Turn on to cap framerate in the loading screen, leave off for load acceleration
bLoadCapping=0 <-- I am sorry but I still don't understand what this does. What are the benefits when ON or Off?
; Turn on to show the mod working, make sure to use windowed mode
bShowDiagnostics=0 <-- What does this do? Show a real time numbers counter on my scree go up and down as the shadows are auto adjusted in real time?
; Uses microsecond precision for target FPS.
bUsePreciseCapping=0 <-- Puts extra stress on the CPU / GPU to keep the FPS at the Target FPS?

Thank you for you hard work.

**Comment by StochasticTinkr** [comment]
I just wrote something  up on the wiki.    https://github.com/StochasticTinkr/PerformanceTuner/wiki

FWIW, bSimpleMode is not used anymore.

**Comment by thericeking** [comment]
To be quite honest I still didn't understand the wiki notes.

Two thing:

1. Does GodRays quality dynamically change? The notes were very confusing because it sounds like implemented but then it says is not.

; !Not Yet Implemented!  bAdjustGRQuality will enable/disable updating of the GR quality.  
; In the current release, it is always enabled.
bAdjustGRQuality=1
; The GR quality shadow distances tell the performance tuner what to set the quality to, given the current shadow distance.
; If the shadow distance is higher than all of the above, GR will be changed to 3.
; This is only supported for 1-3.

2. Can you please keep the option to control FPS from the .ini file? I have a 144Hz monitor and I like to set the FPS to 72 so the voice acting doesn't overlap each other (Known bug for use with 144Hz monitors). Before using your mod I had to use a 3rd party app called "Riva Tuner Statistic Server" to keep my frames cap. With this option I no longer need the extra bloatware.

I appreciate this mod very much. I look forward to your next release.

Thank you

**Comment by StochasticTinkr** [comment]
I've updated the README with even more details, and released a new version.
