### ISSUE TITLE
fShadowDirDistanceMax

### ISSUE THREAD

**Issue by thericeking** [StochasticTinkr/PerformanceTuner#3]
Version: 0.9.0 .ini was set to fShadowDirDistanceMax=20000.0

Version: 0.9.1.ini was set to fShadowDirDistanceMax=12000

Why such a dramatic decrease for fShadowDirDistanceMax?

Thank you for your great contribution to the Fallout community

**Comment by StochasticTinkr** [comment]
These are just the default values, you can change it to whatever you want.
