### ISSUE TITLE
fGRQualityShadowDist

### ISSUE THREAD

**Issue by thericeking** [StochasticTinkr/PerformanceTuner#4]
Version: 0.9.0 had much higher settings

fGRQualityShadowDist1=8000.0
fGRQualityShadowDist2=12000.0
fGRQualityShadowDist3=16000.0

vs

Version: 0.9.1 is much lower

fGRQualityShadowDist1=3000  
fGRQualityShadowDist2=6000  
fGRQualityShadowDist3=10000 

From my understanding the mod doesn't actually try to set the maximum fGRQualityShadowDist when possible. Can you please clarify?

Thank you for your contribution to the Fallout community

**Comment by StochasticTinkr** [comment]
These are just default values, feel free to update them to whatever you want.
