### ISSUE TITLE
New version is out

### ISSUE THREAD

**Issue by Baddest-Juju** [StochasticTinkr/PerformanceTuner#7]
Just letting you know. I'm not playing Fallout 4 at the moment so it's not a big deal to me. There's instructions on how to do it here if someone other than Tinkr wants to do it: https://github.com/StochasticTinkr/PerformanceTuner/issues/5#issuecomment-349138082

At least it's a good update though. New API and stuff to help modders.

**Comment by Cube-13** [comment]
Someone over on Nexus Mods tried the instructions out and came up with some numbers that seem to be working:

fShadowDirDistance=676AA1C
iVolumetricQuality=3902FD8
bGameUpdatePaused=5AA0000
bIsMainMenu=5AA0008
bIsLoading=5A9C340

It was their first time doing something like that so they aren't 100% confident in those numbers.  But they do seem to work :P

**Comment by StochasticTinkr** [comment]
@jsparks40, thanks for that note. I haven't been playing FO4 at all lately (thanks to steam winter sale and a bunch of new games on my PC).

I'll come back to it eventually.  I'm glad I moved those pointers into INI files. This way people can continue to enjoy my mod even though I don't have the time to update it.

**Comment by Baddest-Juju** [comment]
the pointer thing was an amazing idea, yeah.

**Comment by Baddest-Juju** [comment]
Another new version, something about pet support? 0.0.75

edit: gonna start a new issue
